<a href="https://colab.research.google.com/github/arunado/Coursera-Capstone/blob/master/Copy_of_Keraspredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aruna Dorai 13 March 2022


Keras Deep Learning Framework -


One hot encoding is a process of converting categorical data variables so they can be provided to machine learning algorithms to improve predictions. One hot encoding is a crucial part of feature engineering for machine learning.

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding  

define your docuemnts

In [ ]:
mysent = ['How are you', 'How is the weather', 'how is your pet', 'i am fine', 'i live in toronto', 'i have no pets']

categorize and dfine class labels


In [ ]:
mysentlabels = array([1,1,1,0,0,0])

Encoding of documents


In [ ]:
myvocabsiz = 30
encodsent = [one_hot(i,myvocabsiz) for i in mysent]
print(encodsent)


[[22, 1, 7], [22, 29, 29, 3], [22, 29, 14, 27], [15, 4, 19], [15, 8, 13, 17], [15, 7, 21, 23]]


Padding document to max length 5


lenght = 5
padmyencodsent =

In [ ]:
lenght = 5
padmysent = pad_sequences(encodsent, maxlen=lenght,padding='pre')
print(padmysent)

[[ 0  0 22  1  7]
 [ 0 22 29 29  3]
 [ 0 22 29 14 27]
 [ 0  0 15  4 19]
 [ 0 15  8 13 17]
 [ 0 15  7 21 23]]


In [ ]:


mymodel = Sequential()
mymodel.add(Embedding(myvocabsiz, 8, input_length=lenght))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation = 'sigmoid'))



In [ ]:
mymodel.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
mymodel.fit(padmysent,mysentlabels, epochs=30)

Epoch 1/30
1/1 [==============================] - 1s 728ms/step - loss: 0.7089 - accuracy: 0.3333
Epoch 2/30
1/1 [==============================] - 0s 8ms/step - loss: 0.7060 - accuracy: 0.3333
Epoch 3/30
1/1 [==============================] - 0s 6ms/step - loss: 0.7032 - accuracy: 0.3333
Epoch 4/30
1/1 [==============================] - 0s 10ms/step - loss: 0.7003 - accuracy: 0.3333
Epoch 5/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6975 - accuracy: 0.5000
Epoch 6/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6947 - accuracy: 0.5000
Epoch 7/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6919 - accuracy: 0.6667
Epoch 8/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6891 - accuracy: 0.6667
Epoch 9/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6863 - accuracy: 0.6667
Epoch 10/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6835 - accuracy: 0.8333
Epoch 11/30
1/1 [==================

the Prediction part

In [ ]:
topredict =['how tall are you', 'i am short']

In [ ]:
vocab_size = 30
encoded= [one_hot(d, vocab_size) for d in topredict]
print(encoded)

[[22, 29, 1, 7], [15, 4, 25]]


In [ ]:
max_length = 5
mypaded = pad_sequences(encoded, maxlen= max_length, padding='pre')
print(mypaded)



[[ 0 22 29  1  7]
 [ 0  0 15  4 25]]


In [ ]:
ypred = mymodel.predict(mypaded )

In [ ]:
print(ypred)

[[0.5466823 ]
 [0.48987478]]


In [ ]:
topredict =['i am short', 'how tall are you', 'what is your name', 'how are you']


In [ ]:
vocab_size = 30
encoded= [one_hot(d, vocab_size) for d in topredict]
print(encoded)

[[15, 4, 25], [22, 29, 1, 7], [28, 29, 14, 20], [22, 1, 7]]


In [ ]:
max_length = 5
mypaded = pad_sequences(encoded, maxlen= max_length, padding='pre')
print(mypaded)



[[ 0  0 15  4 25]
 [ 0 22 29  1  7]
 [ 0 28 29 14 20]
 [ 0  0 22  1  7]]


In [ ]:
ypred = mymodel.predict(mypaded )

In [ ]:
import numpy as np


In [ ]:
print(np.around(ypred))

[[0.]
 [1.]
 [1.]
 [1.]]
